"""Initial migration with User, Grade, and Subscription tables.

Revision ID: 009cbd2b47ea
Revises:
Create Date: 2025-08-31 19:52:57.208427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009cbd2b47ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calendar_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('wompi_payment_source_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_start_date', sa.DateTime(), nullable=False),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    op.drop_table('user')
    op.drop_table('grade')
    # ### end Alembic commands ###
